parameters:
    carbon.converter.carbon.class: LightSuner\CarbonBundle\Request\ParamConverter\CarbonParamConverter

services:
    carbon.converter.carbon:
        class: %carbon.converter.carbon.class%
        tags:
            - { name: request.param_converter, converter: carbon }
