parameters:
    carbon.form_extension.carbon_date.class: LightSuner\CarbonBundle\Form\Extension\CarbonDateExtension
    carbon.form_extension.carbon_datetime.class: LightSuner\CarbonBundle\Form\Extension\CarbonDateTimeExtension

services:
    carbon.form_extension.carbon_date:
        class: "%carbon.form_extension.carbon_date.class%"
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\DateType }
    carbon.form_extension.carbon_datetime:
        class: "%carbon.form_extension.carbon_datetime.class%"
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\DateTimeType }
